AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 10
      Engine: mysql
      EngineVersion: 8.0.20
      DBInstanceIdentifier: my-db-instance
      MasterUsername: admin
      MasterUserPassword: adminpassword
      DBInstanceClass: db.t2.micro
      AvailabilityZone: us-east-1a

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c94855ba95c71c99  # ID da AMI do Amazon Linux 2
      InstanceType: t2.micro
      KeyName: my-key-pair
      SecurityGroupIds:
        - sg-0123456789abcdef0  # ID do grupo de segurança EC2
      UserData:
        Fn::Base64: |
          #!/bin/bash
          echo "Hello, EC2 instance!"

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-s3-bucket

Outputs:
  RDSInstanceEndpoint:
    Value: !Sub ${MyDBInstance.Endpoint.Address}:${MyDBInstance.Endpoint.Port}
  EC2InstancePublicIP:
    Value: !GetAtt MyEC2Instance.PublicIp
  S3BucketName:
    Value: !Ref MyS3Bucket
